### ISSUE TITLE
[bug] undeclared attribute

### ISSUE THREAD

**Issue by jpdeleon** [danhey/maelstrom#1]
Hi Dan,
Nice package! After pip installation, I tried to run `optimize` but it throws error saying Maelstrom class has no `mean_flux` attribute:
![image](https://user-images.githubusercontent.com/15188345/81479823-bcc89880-9260-11ea-8464-83cbc7bb70fa.png)

**Comment by danhey** [comment]
Thanks Jerome! Actually, you will need to call `ms.setup_orbit_model()` before running optimize. Check out the quick start tutorial here: 
https://danhey.github.io/maelstrom/notebooks/Getting%20started.html#Getting-started
